"""
This file is used to generate new user,
we need to make sure the user generated by this file is not previously registried
##################################################################################
Possible TASKs that require new user each time:
1.REPETITIVE REGISTRATION
2.ADMIN REGISTRATION
"""

import SQL_injection as sqlin

class new_user_generate():

    def __init__(self):
        pass

    def check(self, email):
        """
        This function is used to check whether the email of
        the user is previously registried or not
        return: TRUE if not registried
        """
        test_LoginStatus = sqlin.SQL_injector()
        test_LoginStatus.run(username, new_script)
        new_script = email + "'--"


        test_LoginStatus.change_script(new_script)
        response = test_Login.run()
        if response == 200:



    def generate_email(self):
        """
        This function is used to generate a new user email with some terminology.
        We may use some random function to do this.
        And we will call check function to verify if the email is registried or not
        """
        email_list = ['test8100e@gmail.com', 'test8e99@gmail.com', 'test8e98@gmail.com'
                      ,'test77777@gmail.com']
        idx = 0
        while ( idx < len(email_list) ):
            if self.check(email_list[idx]):
                return email_list[idx]
            else:
                idx += 1
        print("Sorry, we cannot find new user")
